version: '3'

services:

  minio:
    image: minio/minio:latest
    container_name: minio-storage
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: secret
    ports:
      - "9000:9000" # Para conexión con la API y poder guardar las imágenes
      - "9001:9001" # Para abrir la interfaz visual en el navegador
    volumes:
      - ./volume/minio-data:/data
    command: server /data --console-address ":9001"
    
  minio_db:
    image: postgres:14
    container_name: minio-db
    environment:
      POSTGRES_DB: minio
      POSTGRES_USER: minio-user
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - ./volume/minio-db:/var/lib/postgresql/data

  postgres_db:
      image: postgres:14
      container_name: postgres-db
      environment:
        POSTGRES_DB: postgres-db
        POSTGRES_USER: postgres-user
        POSTGRES_PASSWORD: secret
        PGPASSWORD: secret
      ports:
        - "5432:5432"
      restart: always
      volumes:
        - ./volume/postgres-db:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: admin
      restart: unless-stopped
      ports:
        - "5050:80"
      depends_on:
        - postgres_db
        - minio_db
      volumes:
       - ./volume/pgadmin:/var/lib/pgadmin

volumes:
  minio-data:
  minio-db:
  postgres-db:
  pgadmin:
