version: '3'

services:

  minio:
    image: minio/minio:latest
    container_name: minio-storage
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: secretsecret
    ports:
      - "9000:9000" # Para conexión con la API y poder guardar las imágenes
      - "9001:9001" # Para abrir la interfaz visual en el navegador
    volumes:
      - ./minio-data:/data
    restart: always
    command: server --console-address ":9001" /data
    
  minio_db:
    image: postgres:14
    container_name: minio-db
    environment:
      POSTGRES_DB: minio
      POSTGRES_USER: minio-user
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./minio-db:/var/lib/postgresql/data

  postgres_db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

volumes:
  minio-data:  
  minio-db:
  postgres-db: